### PR TITLE
AsciiMath Tranformation Rules 

### LINKED ISSUE #195: Crash in JCGM GUM 6:2020 document
Crash in https://github.com/metanorma/mn-samples-jcgm/issues/35

The crashes are on these formulas:

```
---- FORMULA BEGIN ----
x//
---- FORMULA END ----

---- FORMULA BEGIN ----
u(x)//
---- FORMULA END ----

---- FORMULA BEGIN ----
(u(x)//x)//
---- FORMULA END ----

---- FORMULA BEGIN ----
(u(r)//r)//
---- FORMULA END ----

---- FORMULA BEGIN ----
x = ((I_x + varepsilon_x))/I_"ref" x_"ref"
---- FORMULA END ----
```

Tracked at https://github.com/metanorma/mn-samples-jcgm/issues/35

### PR DESCRIPTION
**Pull request by suleman-uzair**
This PR adds new transformation rules for AsciiMath to fix jcgm#35.

closes #195

### CODE REVIEW

File: lib/plurimath/math/function/text.rb [hunk 1]
```diff
@@ -16,6 +16,7 @@ def to_asciimath
         def to_mathml_without_math_tag
           text = Utility.ox_element("mtext")
           text << (parse_text("mathml") || parameter_one) if parameter_one
+          text
```
Comment (HassanAkbar) [inline lib/plurimath/math/function/text.rb:19]: maybe `return text unless parameter_one` ?

**Review by HassanAkbar — APPROVED** [review]

**Review by ronaldtse — APPROVED** [review]
