### PR TITLE
Mathml and latex parser/transformation rules fixes

### LINKED ISSUE #60: (URGENT) Incorrect parsing of LaTeXmath
I am testing Plurimath::Math.parse(lxm_input, "latex") in metanorma-standoc, branch fix/plurimath. The parsing of LaTeX math is incorrect, and cannot currently be used.

For 

````
Plurimath::Math.parse(lxm_input, "latex").to_mathml
````

````
lxm_input = "M =\n\\begin{bmatrix}\n-\\sin \\lambda_0 & \\cos \\lambda_0 & 0 \\\\\n-\\sin \\varphi_0 \\cos \\lambda_0 & -\\sin \\varphi_0 \\sin \\lambda_0 & \\cos \\varphi_0 \\\\\n\\cos \\varphi_0 \\cos \\lambda_0 & \\cos \\varphi_0 \\sin \\lambda_0 & \\sin \\varphi_0\n\\end{bmatrix}"`
````

Before:

````
               <math xmlns='http://www.w3.org/1998/Math/MathML'>
                 <mrow>
                   <mi>M</mi>
                   <mo>=</mo>
                   <mo>[</mo>
                   <mtable>
                     <mtr>
                       <mtd>
                         <mrow>
                           <mo>−</mo>
                           <mi>sin</mi>
                         </mrow>
                         <msub>
                           <mi>λ</mi>
                           <mn>0</mn>
                         </msub>
                       </mtd>
                       <mtd>
                         <mi>cos</mi>
                         <msub>
                           <mi>λ</mi>
                           <mn>0</mn>
                         </msub>
                       </mtd>
                       <mtd>
                         <mn>0</mn>
                       </mtd>
                     </mtr>
                     <mtr>
                       <mtd>
                         <mrow>
                           <mo>−</mo>
                           <mi>sin</mi>
                         </mrow>
                         <msub>
                           <mi>φ</mi>
                           <mn>0</mn>
                         </msub>
                         <mi>cos</mi>
                         <msub>
                           <mi>λ</mi>
                           <mn>0</mn>
                         </msub>
                       </mtd>
                       <mtd>
                         <mrow>
                           <mo>−</mo>
                           <mi>sin</mi>
                         </mrow>
                         <msub>
                           <mi>φ</mi>
                           <mn>0</mn>
                         </msub>
                         <mi>sin</mi>
                         <msub>
                           <mi>λ</mi>
                           <mn>0</mn>
                         </msub>
                       </mtd>
                       <mtd>
                         <mi>cos</mi>
                         <msub>
                           <mi>φ</mi>
                           <mn>0</mn>
                         </msub>
                       </mtd>
                     </mtr>
                     <mtr>
                       <mtd>
                         <mi>cos</mi>
                         <msub>
                           <mi>φ</mi>
                           <mn>0</mn>
                         </msub>
                         <mi>cos</mi>
                         <msub>
                           <mi>λ</mi>
                           <mn>0</mn>
                         </msub>
                       </mtd>
                       <mtd>
                         <mi>cos</mi>
                         <msub>
                           <mi>φ</mi>
                           <mn>0</mn>
                         </msub>
                         <mi>sin</mi>
                         <msub>
                           <mi>λ</mi>
                           <mn>0</mn>
                         </msub>
                       </mtd>
                       <mtd>
                         <mi>sin</mi>
                         <msub>
                           <mi>φ</mi>
                           <mn>0</mn>
                         </msub>
                       </mtd>
                     </mtr>
                   </mtable>
                   <mo>]</mo>
                 </mrow>
               </math>
````

After:

````
                 <mstyle displaystyle='true'>
                   <mtext>M</mtext>
                   <mo>=</mo>
                   <mfenced open='[' close=']'>
                     <mtable>
                       <mtr>
                         <mtd>
                           <mo>−</mo>
                           <msub>
                             <mi>sin</mi>
                             <mn>0</mn>
                           </msub>
                         </mtd>
                         <mtd>
                           <msub>
                             <mi>cos</mi>
                             <mn>0</mn>
                           </msub>
                         </mtd>
                         <mtd>
                           <mn>0</mn>
                         </mtd>
                       </mtr>
                       <mtr>
                         <mtd>
                           <mo>−</mo>
                           <msub>
                             <mi>sin</mi>
                             <mn>0</mn>
                           </msub>
                           <msub>
                             <mi>cos</mi>
                             <mn>0</mn>
                           </msub>
                         </mtd>
                         <mtd>
                           <mo>−</mo>
                           <msub>
                             <mi>sin</mi>
                             <mn>0</mn>
                           </msub>
                           <msub>
                             <mi>sin</mi>
                             <mn>0</mn>
                           </msub>
                         </mtd>
                         <mtd>
                           <msub>
                             <mi>cos</mi>
                             <mn>0</mn>
                           </msub>
                         </mtd>
                       </mtr>
                       <mtr>
                         <mtd>
                           <msub>
                             <mi>cos</mi>
                             <mn>0</mn>
                           </msub>
                           <msub>
                             <mi>cos</mi>
                             <mn>0</mn>
                           </msub>
                         </mtd>
                         <mtd>
                           <msub>
                             <mi>cos</mi>
                             <mn>0</mn>
                           </msub>
                           <msub>
                             <mi>sin</mi>
                             <mn>0</mn>
                           </msub>
                         </mtd>
                         <mtd>
                           <msub>
                             <mi>sin</mi>
                             <mn>0</mn>
                           </msub>
                         </mtd>
                       </mtr>
                     </mtable>
                   </mfenced>
                 </mstyle>
               </math>
````

* Processing "M = " as `<mtext>` instead of `<mi>` is unacceptable.
* The Greek operands are being quite simply ignored. This is catastrophically wrong.

### PR DESCRIPTION
**Pull request by suleman-uzair**
Updated **MathML** conversion methods and **Latex Parser** and **Transformation** rules.
.
closes #60

### CODE REVIEW

File: spec/plurimath/latex_spec.rb [hunk 1]
```diff
@@ -24,9 +24,8 @@
       let(:string) { '\\cos{45}' }
       it 'returns parsed Latex to Formula' do
         expected_value = Plurimath::Math::Formula.new([
-          Plurimath::Math::Function::Cos.new(
-            Plurimath::Math::Number.new("45")
-          )
+          Plurimath::Math::Symbol.new("cos"),
+          Plurimath::Math::Number.new("45"),
```
Comment (ronaldtse) [inline spec/plurimath/latex_spec.rb:28]: I'm concerned about this change. The previous structure seems more correct to me, and is likely necessary when we do Content MathML (Semantic MathML, not Presentation MathML).

File: lib/plurimath/math/symbol.rb [hunk 2]
```diff
@@ -19,11 +19,20 @@ def to_asciimath
       end
 
       def to_mathml_without_math_tag
-        "<mo>#{mathml_symbol_value}</mo>"
+        mathml_symbol_value
       end
 
       def mathml_symbol_value
-        Mathml::Constants::UNICODE_SYMBOLS.invert[value] || value
+        unicode_symbols = Mathml::Constants::UNICODE_SYMBOLS.invert
```
Comment (ronaldtse) [inline lib/plurimath/math/symbol.rb:26]: Can you extract this into a separate method somewhere? Unicode conversions are probably common.

File: lib/plurimath/math/function/unary_function.rb [hunk 3]
```diff
@@ -24,7 +24,12 @@ def value_to_asciimath
         end
 
         def to_mathml_without_math_tag
-          "<mi>#{class_name}</mi>"
+          <<~LATEX
+            <mrow>
+              <mi>#{class_name}</mi>
+              #{parameter_one&.to_mathml_without_math_tag}
+            </mrow>
+          LATEX
```
Comment (ronaldtse) [inline lib/plurimath/math/function/unary_function.rb:32]: Again I don't think manually typing XML is the correct method to go but we'll see the other parts.

**Review by ronaldtse — CHANGES_REQUESTED** [review]

File: spec/plurimath/latex_spec.rb (hunk 1 above)
Comment (ronaldtse) [reply spec/plurimath/latex_spec.rb:28]: @opoudjis says he did not ask for this change, so let's keep the previous expectation.

File: spec/plurimath/math/formula/mathml_spec.rb [hunk 4]
```diff
@@ -112,7 +112,7 @@
       let(:exp) {
         Plurimath::Math::Formula.new([
           Plurimath::Math::Function::Base.new(
-            Plurimath::Math::Function::Sin.new,
+            Plurimath::Math::Symbol.new("sin"),
```
Comment (ronaldtse) [inline spec/plurimath/math/formula/mathml_spec.rb:115]: Err.. I'm not convinced that this is correct. Sin is **not** a symbol but a function.

File: spec/plurimath/latex_spec.rb (hunk 1 above)
Comment (opoudjis) [reply spec/plurimath/latex_spec.rb:28]: From what I can tell:

* The source in my equation did not use curly brackets: \sin \lambda_0
* Curly brackets are required if the argument is more than one character long: \sin 2x should be \sin{2x}. (That's more obvious for something like y^{2x}
* However, \lambda_0 counts as a single object, so the curly brackets are not needed to make it a single argument of sin
* The LatexMath we have been using until now was processing that with sin as a `<mi>` instead of a `<mo>`. I did not notice that, and that is clearly a bug on their part, which we should not be replicating. Sorry for not spotting it. (That's why I did not list it as an issue to fix.)

* \cos 5 is processed as cos(5), but by that rule of single character arguments, \cos 45 is processed as cos(4) 5
* So properly speaking, \cos 45 is not right, and you are entitled to parse it somehow else
* ... But I still wouldn't

Comment (ronaldtse) [reply spec/plurimath/latex_spec.rb:28]: > ... But I still wouldn't

`\cos 45` ought to be parsed as `cos(45)`. Clearly the string token includes "45". So `cos(45)` is right.

File: spec/plurimath/math/formula/mathml_spec.rb (hunk 4 above)
Comment (opoudjis) [reply spec/plurimath/math/formula/mathml_spec.rb:115]: As noted above, I did not ask for this, this is a bug in LatexMath output which I had not noticed when I raised the ticket.

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thanks @suleman-uzair ! Let's merge this and create new issues for the remaining comments.
